version: '3'
services:
  backend:
    build: ./backend
    container_name: flask-backend
    ports:
      - "1992:1992"
    networks:
      - app-network

  frontend:
    build: ./job-application-portal
    container_name: angular-frontend
    ports:
      - "4200:4200"  # Map container's port 4200 to host's port 4200
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
