version: '3'
services:
  backend:
    build: ./backend
    container_name: flask-backend
    ports:
      - "1992:5000"
    networks:
      - app-network

  frontend:
    build: ./job-application-portal
    container_name: angular-frontend
    ports:
      - "4200:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
